In [1]:
from NLP_Utilities.CoOccurrence_PCA import CoOccurrencePCA
import fitz

def get_text(url):
    # Get the text from a PDF file
    doc = fitz.open(url)

    # Extract text from each page and remove newline characters
    text = "".join([page.get_text().replace("\n", "") for page in doc])

    return text

url_1 = "Data/Texto1.pdf"
url_2 = "Data/Texto2.pdf"
url_3 = "Data/Texto3.pdf"

text_1 = get_text(url_1)
text_2 = get_text(url_2)
text_3 = get_text(url_3)

print(text_1[:100])

(1) En una pequeña ciudad rodeada de montañas nevadas, donde cada invierno parecía más frío que el a

In [3]:
# Crear lista de documentos y nombres
documents = [text_1, text_2, text_3]
doc_names = ["Texto1", "Texto2", "Texto3"]

# Crear una matriz de co-ocurrencia para cada documento
cooccurrence_matrices = {}

for i, (doc, name) in enumerate(zip(documents, doc_names)):

    # Crear instancia para cada documento
    model = CoOccurrencePCA(window_size=2)

    # Procesar solo este documento
    model.fit_transform(docs=[doc], tittles=[name])

    # Calcular matriz de co-ocurrencia
    matrix = model.compute_cooccurrence_matrix()

    # Guardar la matriz
    cooccurrence_matrices[name] = matrix

    print(f"\n{name}:")
    print(f"  Vocabulario: {len(model.vocabulary)} palabras")
    print(f"  Matriz: {matrix.shape}")
    print(f"  Co-ocurrencias totales: {matrix.sum().sum()}")

Texto1:
  Vocabulario: 426 palabras
  Matriz: (426, 426)
  Co-ocurrencias totales: 2798

Texto2:
  Vocabulario: 520 palabras
  Matriz: (520, 520)
  Co-ocurrencias totales: 3134

Texto3:
  Vocabulario: 508 palabras
  Matriz: (508, 508)
  Co-ocurrencias totales: 3622

In [4]:
print("Matriz de co-ocurrencia de Texto 1:")
cooccurrence_matrices["Texto1"]

Matriz de co-ocurrencia de Texto 1:

,1,10,11,12,13,14,15,16,17,18,...,visitar,visitarlo,vitrina,vive,vivia,vivo,voluntad,volvio,voz,vuelto
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
vivo,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
voluntad,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
volvio,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
voz,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
vuelto,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [5]:
print("Matriz de co-ocurrencia de Texto 2:")
cooccurrence_matrices["Texto2"]

Matriz de co-ocurrencia de Texto 2:

,1,10,11,12,13,14,140,15,16,17,...,vida,viento,violeta,visita,visitant,visual,vital,vivo,ypatron,zona
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
visual,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
vital,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
vivo,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
ypatron,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
zona,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
print("Matriz de co-ocurrencia de Texto 3:")
cooccurrence_matrices["Texto3"]

Matriz de co-ocurrencia de Texto 3:

,1,10,11,12,13,14,15,16,17,18,...,viaje,vida,violentamente,vista,vive,viven,vivir,vivo,vuelve,zona
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
viven,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
vivir,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
vivo,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
vuelve,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
zona,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0