## **Exam** - *2° Partial*
* November 24°, 2025
#### ESCOM - IPN: *Natural Language Processing*
#### Prof. Marco Antonio

#### *B.S. in Data Science* - 6AV1

> De la Cruz Carmona Fernando Daniel

> Mendez Carranza Edmundo Ramon

> Rosas Sandoval Gustavo Isaac

> Sánchez García Miguel Alexander

> Villagran Salazar Diego

* Definir la función para extraer los textos

In [1]:
import fitz

def get_text(url):
    # Get the text from a PDF file
    doc = fitz.open(url)

    # Extract text from each page and remove newline characters
    text = "".join([page.get_text().replace("\n", "") for page in doc])  
    
    return text


url_1 = "Data/Texto1.pdf"
url_2 = "Data/Texto2.pdf"
url_3 = "Data/Texto3.pdf"

text_1 = get_text(url_1)
text_2 = get_text(url_2)
text_3 = get_text(url_3)

print(text_1[:100])

(1) En una pequeña ciudad rodeada de montañas nevadas, donde cada invierno parecía más frío que el a

In [2]:
from NLP_Utilities.Tokenizer import Tokenizer

tokenizer = Tokenizer()

text_1_token = tokenizer.tokenize(text_1)

print(text_1_token)

['1', 'pequena', 'ciudad', 'rodeada', 'montana', 'nevada', 'invierno', 'parecia', 'mas', 'frio', 'anterior', 'navidad', 'llegaba', 'envuelta', 'aire', 'nostalgia', 'call', 'adornaban', 'guirnalda', 'color', 'comercio', 'colocaban', 'figura', 'reno', 'muneco', 'nieve', 'vitrina', 'eco', 'villancico', 'resonaba', 'plaza', 'principal', 'callejon', 'mas', 'remoto', 'embargo', 'don', 'esteban', 'viejo', 'relojero', 'vivia', 'casita', 'madera', 'orilla', 'rio', 'navidad', 'tenia', 'significar', '2', 'tre', 'navidad', 'esposa', 'clara', 'habia', 'parter', 'ilevandose', 'consigo', 'iuz', 'iluminaba', 'dia', 'entonc', 'esteban', 'habia', 'dejar', 'encender', 'luc', 'fachada', 'habia', 'dejar', 'preparar', 'chocolate', 'caliente', 'disfrutaban', 'jama', 'volvio', 'colocar', 'arbol', 'navidad', 'guardaba', 'altillo', 'navidad', 'repetia', 'ajustaba', 'engranaj', 'diminuto', 'iuz', 'cansada', 'lampara', '3', 'frio', 'diciembre', 'intensificaba', 'tarde', 'semana', 'navidad', 'nina', 'ocho', 'ano', 'entro', 'taller', 'cargar', 'caja', 'envuelta', 'papel', 'rojo', 'desgastar', 'llevaba', 'gorrito', 'rojo', 'tejer', 'bufanda', 'larga', 'ojo', 'brillaban', 'navidad', 'reflejara', 'senor', 'esteban', 'decir', 'nina', 'voz', 'timida', 'abuela', 'dejo', 'carrusel', 'navidad', 'dejo', 'girar', 'podria', 'arreglarlo', '4', 'anciano', 'observo', 'caja', 'pequena', 'habia', 'carrusel', 'musical', 'decorar', 'figura', 'madera', 'reno', 'angel', 'diminuto', 'casita', 'nevada', 'centro', 'arbol', 'navidad', 'estrella', 'dorada', 'punta', 'desgastar', 'ano', 'conservaba', 'elegancia', 'sencilla', 'encantadora', 'hare', 'pueda', 'respondio', 'esteban', 'intentar', 'ocultar', 'estremecimiento', 'sintio', 'tocar', 'pequeno', 'arbol', 'clara', 'adoraba', 'figurita', '5', 'nina', 'ilamaba', 'lucia', 'dia', 'comenzo', 'visitar', 'taller', 'tarde', 'esteban', 'trabajaba', 'carrusel', 'contaba', 'historia', 'escuela', 'deseo', 'navidad', 'abuela', 'decia', 'navidad', 'iuz', 'apaga', 'esteban', 'incomodaba', 'escuchar', 'navidad', 'dulzura', 'lucia', 'dificil', 'rechazar', 'compania', '6', 'noche', 'reforzaba', 'base', 'carrusel', 'encontro', 'inesperar', 'diminuta', 'inscripcion', 'debajo', 'arbol', 'escrita', 'mano', 'tinta', 'borrosa', 'decia', 'nz', 'navidad', 'vive', 'comparten', 'anciano', 'sintio', 'nudo', 'garganta', 'frase', 'clara', 'repetia', 'ano', 'colocaban', 'arbol', 'habia', 'llegar', 'frase', 'carrusel', '7', 'intrigar', 'decidio', 'arreglar', 'mecanismo', 'tambien', 'restaurar', 'color', 'carrusel', 'retoco', 'detall', 'dorar', 'pulio', 'estrella', 'reforzo', 'soporte', 'arbol', 'pequeno', 'objeto', 'parecia', 'devolverle', 'calor', 'habia', 'perder', '8', 'lucia', 'volvio', 'dia', 'siguiente', 'carrusel', 'giraba', 'perfectamente', 'ai', 'darle', 'cuerda', 'melodia', 'suave', 'calida', 'parecida', 'villancico', 'antiguo', 'lleno', 'taller', 'nina', 'aplaudio', 'entusiasmo', 'soner', 'navidad', 'exclamo', 'mostrare', 'abuela', '9', 'tarde', 'nina', 'volvio', 'ojo', 'brillaban', 'igual', 'abuela', 'enferma', 'decir', 'enferma', 'decir', 'quiza', 'sea', 'ultima', 'navidadjunta', 'anciano', 'sintio', 'dolor', 'profundo', 'El', 'conocia', 'sentimiento', 'conocia', 'despedida', 'anticipada', 'pensar', 'quito', 'gafa', 'decir', 'entonc', 'hagamo', 'navidad', 'sea', 'mas', 'luminosa', 'posible', '10', 'partir', 'dia', 'taller', 'convirtio', 'refugio', 'navideno', 'lucia', 'decoraba', 'frasco', 'cristal', 'estrella', 'recortaba', 'copo', 'nieve', 'papel', 'pintaba', 'pequena', 'figura', 'esteban', 'trabajaba', 'reloj', 'mecanismo', 'primera', 'vez', 'ano', 'anciano', 'coloco', 'guirnalda', 'escaparate', 'sencilla', 'brillaba', 'resplandor', 'inesperar', '11', 'vecino', 'sorprender', 'ver', 'luc', 'viejo', 'taller', 'comenzaron', 'visitarlo', 'llevaban', 'adorno', 'roto', 'reparar', 'simplemente', 'querian', 'saludar', 'navidad', 'parecia', 'colarse', 'rendija', 'iugar', 'ciudad', 'entera', 'noto', 'cambio', 'especial', 'ocurrer', '12', 'tarde', 'lucia', 'entro', 'correr', 'senor', 'esteban', 'abuela', 'quiere', 'verlo', 'dice', 'importante', 'decirle', 'navidad', 'anciano', 'desconcertar', 'acompano', 'casa', 'encontro', 'mujer', 'grande', 'recostada', 'manta', 'carrusel', 'restaurar', 'mesa', '13', 'asi', 'relojero', 'decir', 'anciana', 'voz', 'debii', 'carrusel', 'pertenecio', 'madre', 'abuela', 'entregamo', 'alguien', 'necesita', 'recordar', 'navidad', 'esteban', 'estremecio', 'anciana', 'sonrio', 'navidadvuelve', 'olvidar', 'iuz', 'lucia', 'decir', 'celebraba', 'navidad', 'ano', 'carrusel', 'destinar', 'devolverla', '14', 'noche', 'esteban', 'regreso', 'casa', 'silencio', 'encendio', 'vela', 'ventana', 'solia', 'clara', 'sabia', 'parecio', 'correcto', 'ilama', 'parpadeaba', 'anciano', 'recordo', 'risa', 'esposa', 'cancion', 'navidad', 'forma', 'decoraba', 'arbol', 'cuidar', 'lagrima', 'habia', 'guardar', 'finalmente', 'escaparon', '15', 'dia', 'siguient', 'ciudad', 'preparo', 'tormenta', 'navidad', 'semana', 'distancia', 'lucia', 'iba', 'taller', 'cuidaba', 'abuela', 'empeoraba', 'lentamente', 'asi', 'encontraba', 'momento', 'encender', 'pequena', 'estrella', 'carrusel', 'navidad', 'sigue', 'aqui', 'decia', 'esteban', 'enseno', '16', 'tormenta', 'estallo', 'noche', '23', 'diciembre', 'nieve', 'caia', 'furia', 'luc', 'apagaron', 'ciudad', 'frio', 'colo', 'rincon', 'esteban', 'salio', 'casa', 'linterna', 'corrio', 'lucia', 'ai', 'llegar', 'encontro', 'nina', 'llorar', 'abuela', 'susurro', 'desperto', 'anciano', 'abrazo', 'silencio', 'oscuridad', 'parecia', 'mas', 'profunda', 'navidad', 'habia', 'renacer', 'parecia', 'extinguirse', 'vez', '17', 'entonc', 'esteban', 'recordo', 'frase', 'inscrita', 'carrusel', 'iuz', 'navidad', 'vive', 'comparten', 'levanto', 'tomo', 'mano', 'lucia', 'decir', 'hagamo', 'iuz', 'siga', 'brillar', '18', 'corrieron', 'taller', 'pesar', 'apagon', 'anciano', 'encendio', 'docena', 'vela', 'lampara', 'aceite', 'iuz', 'calida', 'ilumino', 'ventana', 'proyectar', 'sombra', 'danzant', 'nieve', 'coloco', 'carrusel', 'centro', 'mostrador', 'ai', 'darle', 'cuerda', 'melodia', 'extendio', 'calle', 'tenue', 'constante', '19', 'vecino', 'ver', 'iuz', 'escuchar', 'musica', 'comenzaron', 'salir', 'casa', 'ilevaron', 'farol', 'antorcha', 'improvisada', 'hora', 'calle', 'iluminada', 'gente', 'cantaba', 'villancico', 'tormenta', 'saberlo', 'habian', 'crear', 'nueva', 'tradicion', 'marcha', 'navidad', '20', 'medianoche', 'llego', 'tormenta', 'calmo', 'calle', 'oscura', 'brillaba', 'iuz', 'vela', 'podria', 'explicar', 'navidad', 'habia', 'vuelto', 'milagro', 'voluntad', 'decidieron', 'compartir', 'ilama', '21', 'lucia', 'sostener', 'mano', 'esteban', 'miro', 'cielo', 'estrellar', 'susurro', 'abuela', 'estaria', 'feliz', 'anciano', 'sonrio', 'clara', 'tambien', 'primera', 'vez', 'ano', 'esteban', 'sintio', 'navidad', 'recuerdo', 'presente', 'vivo', '22', 'ai', 'ano', 'siguiente', 'ano', 'despu', 'ciudad', 'repitio', 'marcha', 'navidad', 'carrusel', 'permanecio', 'taller', 'lucia', 'crecio', 'visitandolo', 'navidad', 'asegurandose', 'iuz', 'apagara', '23', 'vida', 'siguio', 'curso', 'cosa', 'cambio', 'pequena', 'ciudad', 'navidad', 'brillaba', 'mas', 'ningun', 'iugar']

In [6]:
lemmas = "correr, corriendo, corrimos, corriamos, correriamos, niños, niño, niña, comidas, comer, comiendo, limpiando"

token = tokenizer.tokenize(lemmas)

print(token)

['correr', 'correr', 'corrimo', 'corriamo', 'correriamo', 'nino', 'nino', 'nina', 'comida', 'comer', 'comer', 'limpiar']

#### **a)** Obtener la matriz de co-ocurrencia para cada texto

#### **b)** Eliminar stopwords vía expresiones regulares (se permite librerias), generar un nuevo pdf para visualzizar el resultado

#### **c)** Que el usuario ingrese una palabra y través de similitud coseno se determine cuál es el texto más asemejado. Realizar toda la etapa de preprocesamiento con sus programas anteriores.

#### **d)** Para cada texto, determinar su tema principal.

**For each text document we will obtain the co-ocurrence matriz so we will be able tu visualize the most defined concepts on the 3D Plot; in addition we will obtain the TF_IDF matrix to get the most relevant word. With this we can conclude which is the principal topic of the document with the help of the two metrics**

* For the **1°** document

In [4]:
from NLP_Utilities.CoOccurrence_PCA import CoOccurrencePCA

co_ocurrence = CoOccurrencePCA()

# For the first text
co_ocurrence.fit_transform(docs=[text_1])

co_text_1 = co_ocurrence.compute_cooccurrence_matrix()

co_text_1

,1,10,11,12,13,14,15,16,17,18,...,visitar,visitarlo,vitrina,vive,vivia,vivo,voluntad,volvio,voz,vuelto
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
vivo,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
voluntad,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
volvio,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
voz,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
vuelto,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [6]:
co_ocurrence.apply_pca()

co_ocurrence.plot_3d_interactive()

In [7]:
from NLP_Utilities.TF_IDF import TF_IDF

# For the first text
tf_idf = TF_IDF()

tf_idf.fit_transform(docs=[text_1])

tf_idf_1 = tf_idf.compute_tf_idf()

# Order the columns to get the most relevant words
tf_idf_1_numeric = tf_idf_1.select_dtypes(include='number')

tf_idf_1_sorted = tf_idf_1_numeric.sort_values(by=tf_idf_1_numeric.index[0], axis=1, ascending=True)

tf_idf_1_sorted

,navidad,esteban,carrusel,lucia,iuz,habia,abuela,anciano,ano,taller,...,entera,enseno,engranaj,encontraba,encantadora,empeoraba,embargo,elegancia,dulzura,vuelto
Document 1,-20.794415,-10.397208,-9.704061,-7.624619,-6.931472,-6.238325,-6.238325,-6.238325,-5.545177,-5.545177,...,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147

> We can assume that the principal topic for the first document is "navidad" and a story related to christmas

* For the **2°** document

In [8]:
co_ocurrence = CoOccurrencePCA()

# For the first text
co_ocurrence.fit_transform(docs=[text_2])

co_text_2 = co_ocurrence.compute_cooccurrence_matrix()

co_text_2

,1,10,11,12,13,14,140,15,16,17,...,vida,viento,violeta,visita,visitant,visual,vital,vivo,ypatron,zona
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
visual,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
vital,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
vivo,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
ypatron,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
zona,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
co_ocurrence.apply_pca()

co_ocurrence.plot_3d_interactive()

In [10]:
# For the second text
tf_idf = TF_IDF()

tf_idf.fit_transform(docs=[text_2])

tf_idf_2 = tf_idf.compute_tf_idf()

# Order the columns to get the most relevant words
tf_idf_2_numeric = tf_idf_2.select_dtypes(include='number')

tf_idf_2_sorted = tf_idf_2_numeric.sort_values(by=tf_idf_2_numeric.index[0], axis=1, ascending=True)

tf_idf_2_sorted

,flor,polinizador,color,nectar,especi,estructura,insecto,mas,planta,forma,...,descubrir,descubrio,desarrollo,desarrollar,desaparecieran,desaparece,desajuste,desagradabl,dependian,fascinar
Document 1,-47.827155,-9.704061,-5.545177,-4.158883,-4.158883,-4.158883,-4.158883,-3.465736,-3.465736,-2.772589,...,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147

> We can assume that the principal topic of the second document is "flor" and something related to flowers

* For the **3°** document

In [11]:
co_ocurrence = CoOccurrencePCA()

# For the first text
co_ocurrence.fit_transform(docs=[text_3])

co_text_3 = co_ocurrence.compute_cooccurrence_matrix()

co_text_3

,1,10,11,12,13,14,15,16,17,18,...,viaje,vida,violentamente,vista,vive,viven,vivir,vivo,vuelve,zona
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
viven,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
vivir,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
vivo,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
vuelve,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
zona,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
co_ocurrence.apply_pca()

co_ocurrence.plot_3d_interactive()

In [13]:
# For the third text
tf_idf = TF_IDF()

tf_idf.fit_transform(docs=[text_3])

tf_idf_3 = tf_idf.compute_tf_idf()

# Order the columns to get the most relevant words
tf_idf_3_numeric = tf_idf_3.select_dtypes(include='number')

tf_idf_3_sorted = tf_idf_3_numeric.sort_values(by=tf_idf_3_numeric.index[0], axis=1, ascending=True)

tf_idf_3_sorted

,estrella,mas,nucleo,masa,vida,ano,universo,millon,luz,son,...,estelar,estable,espectro,esfera,esencial,escrita,escenario,escapar,envolvera,zona
Document 1,-62.383246,-11.783502,-7.624619,-6.931472,-6.931472,-5.545177,-5.545177,-5.545177,-5.545177,-4.85203,...,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147,-0.693147

> We can assume that the principal topic is "estrella" or something related to the stars, space and the universe